maxsize: 10
minsize: 1
noplayer: "§cUse this command ingame"
noperms: "§cYou dont have Permission to do this"
sizeusage: "§cUse /size <scale>"
sizeistobig: "§cPls but a size from 1-10"
sizenonumber: "§Use /size <scale>"
sizesucces: "§aYou have succesfully changed you size to §e{size}"
